blank_issues_enabled: false
contact_links:
  - name: Gateway Issue Template
    url: https://github.com/UbiqiSense/Gateway/issues/new?template=ubiqisense-gateway-template.md
    about: Use this for gateway-related updates or issues.
